services:
  ros-noetic-desktop-full:
    image: ghcr.io/lxk36/xgc2-app-store/ros-noetic-desktop-full:1.0.0
    container_name: ${CONTAINER_NAME}
    network_mode: host
    restart: unless-stopped
    environment:
      DISPLAY: ${DISPLAY:-}
      XAUTHORITY: ${XAUTHORITY:-}
      ROS_WORKSPACE: ${ROS_WORKSPACE}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XGC_HOST_WORKSPACE_DIR}/${ROS_WORKSPACE}:/home/ros_ws
    stdin_open: true
    tty: true
    command: ["bash", "-lc", "source /opt/ros/noetic/setup.bash && sleep infinity"]
