services:
  ros-jazzy-desktop-full:
    image: ghcr.io/lxk36/xgc2-app-store/ros-jazzy-desktop-full:1.0.0
    container_name: ${CONTAINER_NAME}
    network_mode: host
    restart: unless-stopped
    environment:
      DISPLAY: ${DISPLAY:-}
      XAUTHORITY: ${XAUTHORITY:-}
      ROS2_WORKSPACE: ${ROS2_WORKSPACE}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XGC_HOST_WORKSPACE_DIR}/${ROS2_WORKSPACE}:/workspace
    stdin_open: true
    tty: true
    command: ["bash", "-lc", "source /opt/ros/jazzy/setup.bash && sleep infinity"]
